-- Busihub — 0015: inventory (Phase 6, core stock tracking)
--
-- Design follows docs/ARCHITECTURE.md §"Inventory integrity" exactly:
-- stock quantity is NEVER edited directly. Every change is an immutable
-- inventory_movements row (reason + signed delta + who/when), and
-- stock_levels is a derived aggregate maintained by a trigger inside the
-- same transaction as the movement. That gives a true audit trail — "why
-- is there 7 of these?" is always answerable — instead of a mutable
-- counter that silently drifts.
--
-- Scope of this phase (agreed before building): per-branch stock levels,
-- the movements ledger, and manual entry — receive stock, adjust with a
-- reason, and record a physical stock count. Branch-to-branch transfers
-- and low-stock reorder points are deliberately NOT here; the `reason`
-- CHECK below already reserves their values so adding them later is a
-- policy change, not a schema migration.
--
-- Stock is tracked for EVERY variant (no per-product opt-in toggle), so
-- there is no conditional "is this tracked?" path through any of the
-- operations below.
--
-- Permission model (all four already exist in the 0010 catalog and are
-- already assigned to roles in 0011 — no catalog change needed here):
--   inventory.view     — see stock levels and the movement history.
--   inventory.receive  — record stock coming in (reason = 'receive').
--   inventory.adjust   — correct stock (reason = 'adjustment') and record
--                        a physical count (reason = 'stock_count').
--   inventory.transfer — reserved for the transfers phase; no movement
--                        reason accepts it yet, so it currently grants
--                        nothing. Intentional.
--
-- Note on rows that don't exist: a variant/branch pair with no movements
-- yet simply has no stock_levels row, and is read as quantity 0. The
-- alternative — pre-creating one row per variant × branch — would mean
-- backfills plus triggers on both new variants and new branches, for no
-- behavioural gain. Every read path below LEFT JOINs and coalesces.

-- ── movements ledger (append-only) ───────────────────────────────────────

create table inventory_movements (
  id             uuid primary key default gen_random_uuid(),
  -- Denormalized from the branch by the trigger below (never trust a
  -- client-supplied value) so RLS can scope this table directly — same
  -- rationale as product_variants.business_id in 0013.
  business_id    uuid not null references businesses(id) on delete cascade,
  branch_id      uuid not null references branches(id) on delete restrict,
  variant_id     uuid not null references product_variants(id) on delete restrict,
  -- Signed. Positive = stock in, negative = stock out. numeric(14,3)
  -- rather than an integer because products carry a unit_of_measure and
  -- some of them are weighed (kg, litres), not counted.
  quantity_delta numeric(14, 3) not null check (quantity_delta <> 0),
  reason         text not null check (reason in (
                   -- insertable in this phase:
                   'receive', 'adjustment', 'stock_count',
                   -- reserved for later phases; no RLS policy admits them
                   -- yet, so an insert claiming one is rejected:
                   'sale', 'sale_refund', 'transfer_in', 'transfer_out'
                 )),
  -- What caused this, for movements generated by another record (a sale,
  -- a transfer) rather than typed in by a person. Null for manual entry.
  reference_type text,
  reference_id   uuid,
  note           text,
  created_by     uuid references profiles(id) on delete set null,
  created_at     timestamptz not null default now()
);

-- No updated_at and no set_updated_at trigger: rows here are immutable.
-- That is enforced properly further down (no update/delete RLS policy AND
-- the grants revoked), not just implied by the absence of a column.

create index inventory_movements_business_created_idx
  on inventory_movements (business_id, created_at desc);
create index inventory_movements_variant_branch_created_idx
  on inventory_movements (variant_id, branch_id, created_at desc);
create index inventory_movements_branch_idx on inventory_movements (branch_id);

comment on table inventory_movements is
  'Append-only ledger of every stock change. Never updated or deleted — a correction is a new row with an opposing delta. stock_levels is derived from this by apply_inventory_movement().';

-- ── derived stock levels ─────────────────────────────────────────────────

create table stock_levels (
  business_id uuid not null references businesses(id) on delete cascade,
  branch_id   uuid not null references branches(id) on delete cascade,
  variant_id  uuid not null references product_variants(id) on delete cascade,
  quantity    numeric(14, 3) not null default 0,
  updated_at  timestamptz not null default now(),
  primary key (branch_id, variant_id)
);

create index stock_levels_business_idx on stock_levels (business_id);
create index stock_levels_variant_idx on stock_levels (variant_id);

comment on table stock_levels is
  'Derived aggregate — the current quantity of one variant at one branch. Written ONLY by apply_inventory_movement() (a SECURITY DEFINER trigger); users have no insert/update/delete grant on this table at all, so stock cannot be set directly even by a caller that bypasses the app entirely.';

-- ── business_id / tenancy forcing ────────────────────────────────────────

create or replace function set_inventory_movement_context()
returns trigger
language plpgsql
as $$
declare
  v_branch_business  uuid;
  v_variant_business uuid;
begin
  select business_id into v_branch_business from branches where id = new.branch_id;
  if v_branch_business is null then
    raise exception 'Invalid branch_id: branch not found' using errcode = 'P0002';
  end if;

  select business_id into v_variant_business from product_variants where id = new.variant_id;
  if v_variant_business is null then
    raise exception 'Invalid variant_id: product variant not found' using errcode = 'P0002';
  end if;

  -- Both lookups above are themselves RLS-scoped (this function is
  -- SECURITY INVOKER by design), so another tenant's branch or variant
  -- already reads as "not found". This explicit cross-check catches the
  -- remaining case: a caller who legitimately belongs to two businesses
  -- pairing a branch from one with a variant from the other.
  if v_branch_business <> v_variant_business then
    raise exception 'Branch and product belong to different businesses' using errcode = 'P0001';
  end if;

  new.business_id := v_branch_business;
  -- Attribution is taken from the session, never from the payload.
  new.created_by := auth.uid();

  return new;
end;
$$;

comment on function set_inventory_movement_context() is
  'Forces inventory_movements.business_id to match the branch (and requires the variant to be in that same business), and stamps created_by from the session. Runs BEFORE INSERT so the RLS WITH CHECK below evaluates the corrected business_id, not whatever the caller sent.';

create trigger set_movement_context
  before insert on inventory_movements
  for each row execute function set_inventory_movement_context();

-- ── the derived-aggregate trigger ────────────────────────────────────────

create or replace function apply_inventory_movement()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_new_quantity numeric(14, 3);
begin
  -- One atomic statement: the ON CONFLICT path takes a row lock on the
  -- existing stock_levels row for the rest of the transaction, so two
  -- concurrent movements against the same variant/branch serialize here
  -- rather than both reading the same "before" value. This is the row
  -- locking ARCHITECTURE.md calls for, expressed as an upsert instead of
  -- a separate SELECT … FOR UPDATE (same guarantee, one round trip, and
  -- it also handles the "no row yet" case without a race).
  insert into stock_levels (business_id, branch_id, variant_id, quantity, updated_at)
  values (new.business_id, new.branch_id, new.variant_id, new.quantity_delta, now())
  on conflict (branch_id, variant_id) do update
    set quantity   = stock_levels.quantity + excluded.quantity,
        updated_at = now()
  returning quantity into v_new_quantity;

  -- Rejecting here (rather than a CHECK on the column) keeps the rule in
  -- one place and lets a later phase relax it deliberately: offline sale
  -- sync (Phase 17) is specified to ACCEPT a movement that drives stock
  -- negative — the sale physically happened in the shop — and flag the
  -- result as an alert instead of rejecting it. Manual entry, which is
  -- all this phase admits, has no such excuse.
  if v_new_quantity < 0 then
    raise exception 'Not enough stock: this would leave % on hand', v_new_quantity
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

comment on function apply_inventory_movement() is
  'AFTER INSERT on inventory_movements: applies the delta to stock_levels in the same transaction. SECURITY DEFINER because stock_levels deliberately grants users no write access — this trigger is its only writer.';

create trigger apply_movement
  after insert on inventory_movements
  for each row execute function apply_inventory_movement();

-- ── RLS ──────────────────────────────────────────────────────────────────

alter table inventory_movements enable row level security;

create policy inventory_movements_select on inventory_movements
  for select
  using (app_has_permission(business_id, 'inventory.view') or app_is_super_admin());

-- The permission required depends on WHY the stock is moving, so this is
-- a per-reason check rather than one coarse OR. The reasons reserved for
-- later phases ('sale', 'transfer_in', …) match no branch here and are
-- therefore rejected — they'll get their own policy when the phase that
-- generates them lands.
create policy inventory_movements_insert on inventory_movements
  for insert
  with check (
    app_is_super_admin()
    or (reason = 'receive' and app_has_permission(business_id, 'inventory.receive'))
    or (reason in ('adjustment', 'stock_count') and app_has_permission(business_id, 'inventory.adjust'))
  );

-- No update and no delete policy: the ledger is append-only. Belt and
-- braces, since RLS only filters what a granted statement can reach —
-- without the grant the statement is refused outright.
revoke update, delete on inventory_movements from authenticated;

alter table stock_levels enable row level security;

create policy stock_levels_select on stock_levels
  for select
  using (app_has_permission(business_id, 'inventory.view') or app_is_super_admin());

-- Deliberately NO insert/update/delete policy, and the grants removed:
-- stock_levels is derived state. The only writer is
-- apply_inventory_movement() above, which is SECURITY DEFINER and so runs
-- as the table owner regardless of these.
revoke insert, update, delete on stock_levels from authenticated;

-- ── record_stock_count(): absolute count → relative movement ─────────────
--
-- Receiving and adjusting are naturally relative ("+12", "-2 damaged") and
-- so are plain inserts. A physical stock count is the odd one out: the
-- user knows the ABSOLUTE number on the shelf, and the ledger needs the
-- delta that gets there from wherever the system currently thinks it is.
-- Computing that in the app would be a read-then-write race — two people
-- counting the same item at once would each compute a delta from the same
-- stale "before" value and the second would overwrite the first.
--
-- The advisory lock serializes the read-and-insert for one (branch,
-- variant) pair. It is used rather than SELECT … FOR UPDATE because on a
-- first-ever count there is no stock_levels row yet to lock, and a lock
-- on a row that doesn't exist prevents nothing.
--
-- SECURITY INVOKER (the default) on purpose, exactly like create_product
-- in 0013: it runs as the caller, so the RLS policy above is what decides
-- whether the movement is allowed — that is also what stops p_branch_id
-- from being pointed at another tenant.
create or replace function record_stock_count(
  p_branch_id uuid,
  p_variant_id uuid,
  p_counted_quantity numeric,
  p_note text default null
)
returns uuid
language plpgsql
as $$
declare
  v_current  numeric(14, 3);
  v_delta    numeric(14, 3);
  v_movement uuid;
begin
  if p_counted_quantity is null or p_counted_quantity < 0 then
    raise exception 'Counted quantity must be zero or more' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_branch_id::text || ':' || p_variant_id::text, 0)
  );

  select coalesce(quantity, 0) into v_current
  from stock_levels
  where branch_id = p_branch_id and variant_id = p_variant_id;

  v_current := coalesce(v_current, 0);
  v_delta := p_counted_quantity - v_current;

  -- A count that matches the system exactly is a no-op, not an error.
  -- quantity_delta has a `<> 0` check, so there is nothing to record.
  if v_delta = 0 then
    return null;
  end if;

  insert into inventory_movements (branch_id, variant_id, quantity_delta, reason, note, business_id)
  values (p_branch_id, p_variant_id, v_delta, 'stock_count', nullif(p_note, ''),
          -- overwritten by set_inventory_movement_context(); a non-null
          -- placeholder is needed only to satisfy the NOT NULL before the
          -- BEFORE trigger runs.
          '00000000-0000-0000-0000-000000000000')
  returning id into v_movement;

  return v_movement;
end;
$$;

grant execute on function record_stock_count(uuid, uuid, numeric, text) to authenticated;

comment on function record_stock_count(uuid, uuid, numeric, text) is
  'Records a physical stock count as a relative movement, serialized per (branch, variant) by an advisory lock so two simultaneous counts cannot both compute a delta from the same stale value. Returns the movement id, or null when the count already matched.';
